# Generated by Django 5.1.1 on 2024-11-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='brand_name',
            field=models.ForeignKey(default='men', on_delete=django.db.models.deletion.CASCADE, related_name='a', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='brandbnnr',
            name='brand_name',
            field=models.ForeignKey(default='women', on_delete=django.db.models.deletion.CASCADE, related_name='c', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='card',
            name='banner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i', to='app.banners'),
        ),
        migrations.AlterField(
            model_name='card',
            name='brnd_bn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k', to='app.brandbnnr'),
        ),
        migrations.AlterField(
            model_name='card',
            name='menban_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j', to='app.menban'),
        ),
        migrations.AlterField(
            model_name='card',
            name='shoes_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m', to='app.shoes'),
        ),
        migrations.AlterField(
            model_name='card',
            name='wbanner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l', to='app.wbanner'),
        ),
        migrations.AlterField(
            model_name='card',
            name='wcard2_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o', to='app.hwomencard2'),
        ),
        migrations.AlterField(
            model_name='card',
            name='wcard_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n', to='app.hwomencard'),
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='brand_name',
            field=models.ForeignKey(default='men', on_delete=django.db.models.deletion.CASCADE, related_name='h', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='hwomencard',
            name='brand_name',
            field=models.ForeignKey(default='polo', on_delete=django.db.models.deletion.CASCADE, related_name='e', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='hwomencard2',
            name='brand_name',
            field=models.ForeignKey(default='trend', on_delete=django.db.models.deletion.CASCADE, related_name='f', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='menban',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='brand_name',
            field=models.ForeignKey(default='asian', on_delete=django.db.models.deletion.CASCADE, related_name='g', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='wbanner',
            name='brand_name',
            field=models.ForeignKey(default='levis', on_delete=django.db.models.deletion.CASCADE, related_name='d', to='app.brand'),
        ),
    ]
