# Generated by Django 5.1.1 on 2024-11-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_banners_brand_name_alter_brandbnnr_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='brnd_bn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbnr', to='app.brandbnnr'),
        ),
    ]
