# Generated by Django 5.1.1 on 2024-11-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_card_frag_name_mbanner_delete_fragrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mbanner_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mb', to='app.mbanner'),
            preserve_default=False,
        ),
    ]
