# Generated by Django 5.1.1 on 2024-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_card_mbanner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwomencard',
            name='wcard_name',
            field=models.CharField(default='women', max_length=50),
        ),
        migrations.AlterField(
            model_name='hwomencard2',
            name='wcard2_name',
            field=models.CharField(default='boys', max_length=50),
        ),
    ]
