# Generated by Django 5.1.1 on 2024-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_hwomencard_wcard_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='fname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='lname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
