# Generated by Django 5.1.1 on 2024-11-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sign_fname_sign_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lname',
            new_name='last_name',
        ),
    ]
