# Generated by Django 5.1.1 on 2024-11-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_fname_sign_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='sizep',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
