# Generated by Django 5.1.1 on 2024-11-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wishlist_sizep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='sizep',
        ),
    ]
