# Generated by Django 5.1.1 on 2024-11-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_wishlist_sizep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
