# Generated by Django 5.1.1 on 2024-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rating',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
