# Generated by Django 4.2.18 on 2025-02-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_card_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
