# Generated by Django 4.2.18 on 2025-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='Phoneno1',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='alterPhone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
